# ── Cloud Build CI/CD Pipeline for Maa Ki Rasoi ───────────────────────────
# Triggers on push to main branch.
# Builds backend Docker image → deploys to Cloud Run (Mumbai)
# Builds all 3 frontend SPAs → deploys to Firebase Hosting

substitutions:
  _REGION: asia-south1
  _SERVICE: maa-ki-rasoi-api
  _REPO: maa-ki-rasoi
  _PROJECT_ID: ${PROJECT_ID}  # Auto-injected by Cloud Build

steps:
  # ── BACKEND ─────────────────────────────────────────────────────────────

  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - build
      - -t
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/api:${SHORT_SHA}'
      - -t
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/api:latest'
      - .

  # Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - push
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/api'
    waitFor: ['build-image']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-backend'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - '${_SERVICE}'
      - '--image=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/api:${SHORT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--min-instances=1'
      - '--max-instances=10'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--port=8080'
      - '--set-secrets=DATABASE_URL=DATABASE_URL:latest,JWT_SECRET=JWT_SECRET:latest,FAST2SMS_API_KEY=FAST2SMS_API_KEY:latest,RAZORPAY_KEY_ID=RAZORPAY_KEY_ID:latest,RAZORPAY_KEY_SECRET=RAZORPAY_KEY_SECRET:latest,CORS_ORIGIN=CORS_ORIGIN:latest'
    waitFor: ['push-image']

  # ── FRONTEND: CUSTOMER ───────────────────────────────────────────────────

  # Step 4: Build customer PWA
  - name: 'node:20-alpine'
    id: 'build-customer'
    entrypoint: sh
    args:
      - -c
      - 'cd apps/customer && npm ci && npm run build'
    env:
      - 'VITE_API_URL=https://${_SERVICE}-${_PROJECT_ID}.run.app'
    waitFor: ['-']  # Run in parallel with backend

  # Step 5: Deploy customer to Firebase
  - name: 'node:20-alpine'
    id: 'deploy-customer'
    entrypoint: sh
    args:
      - -c
      - 'npm install -g firebase-tools && cd apps/customer && firebase deploy --only hosting --token=$$FIREBASE_TOKEN --project=${_PROJECT_ID}'
    secretEnv: ['FIREBASE_TOKEN']
    waitFor: ['build-customer']

  # ── FRONTEND: ADMIN ──────────────────────────────────────────────────────

  # Step 6: Build admin panel
  - name: 'node:20-alpine'
    id: 'build-admin'
    entrypoint: sh
    args:
      - -c
      - 'cd apps/admin && npm ci && npm run build'
    env:
      - 'VITE_API_URL=https://${_SERVICE}-${_PROJECT_ID}.run.app'
    waitFor: ['-']

  # Step 7: Deploy admin to Firebase
  - name: 'node:20-alpine'
    id: 'deploy-admin'
    entrypoint: sh
    args:
      - -c
      - 'npm install -g firebase-tools && cd apps/admin && firebase deploy --only hosting --token=$$FIREBASE_TOKEN --project=${_PROJECT_ID}'
    secretEnv: ['FIREBASE_TOKEN']
    waitFor: ['build-admin']

  # ── FRONTEND: DELIVERY ───────────────────────────────────────────────────

  # Step 8: Build delivery app
  - name: 'node:20-alpine'
    id: 'build-delivery'
    entrypoint: sh
    args:
      - -c
      - 'cd apps/delivery && npm ci && npm run build'
    env:
      - 'VITE_API_URL=https://${_SERVICE}-${_PROJECT_ID}.run.app'
    waitFor: ['-']

  # Step 9: Deploy delivery to Firebase
  - name: 'node:20-alpine'
    id: 'deploy-delivery'
    entrypoint: sh
    args:
      - -c
      - 'npm install -g firebase-tools && cd apps/delivery && firebase deploy --only hosting --token=$$FIREBASE_TOKEN --project=${_PROJECT_ID}'
    secretEnv: ['FIREBASE_TOKEN']
    waitFor: ['build-delivery']

# Secret: Firebase CI token (stored in Secret Manager)
availableSecrets:
  secretManager:
    - versionName: projects/${_PROJECT_ID}/secrets/FIREBASE_TOKEN/versions/latest
      env: 'FIREBASE_TOKEN'

# Store the Docker image in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/api:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/api:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # Faster parallel builds

timeout: '1200s'  # 20 min max build time
